### ISSUE TITLE
Minion

### ISSUE THREAD

**Issue by colindaven** [CFSAN-Biostatistics/porerefiner#2]
Hi,

interesting, we're looking for some sort of simple Minion run tracker/LIMS.

Is this software just restricted to Gridion or can it cope with the other platforms too ?

Thanks

**Comment by crashfrog** [comment]
It's actually pretty agnostic to the platform; it makes an assumption that under some filesystem location, the instrument is making a nested series of folders for instrument data that look like

    [EXPERIMENT_ID]/[SAMPLE_ID]/[START_TIME]_[DEVICE_ID]_[FLOWCELL_ID]_[SHORT_PROTOCOL_RUN_ID]

and then with data files underneath that. I think the Minion works that way, too, so it'll probably work out of the box (to the extent that the software currently does work, which is "mostly.")
